### ISSUE TITLE
Gencode genome

### ISSUE THREAD

**Issue by CharlotteAnne** [jpaggi/labranchor#1]
Hi!

Thank you for a wonderful tool.

Just a note to anyone using a genome fasta downloaded from Gencode - the format of the chromosome header lines is e.g. >chr1 1, so the create_fasta.py will fall down because the chromosome names don't match to the annotation.

To solve this I added .split(" ")[0] to the genome parser function, see below:

class Genome:
    def __init__(self, fasta_fn):
        self.genome = {}
        with open(fasta_fn) as fp:
            chrom = fp.readline().strip()[1:]**.split(" ")[0]**
            print(chrom)
            seq = ''
            for line in fp:
                if line[0] == '>':
                    self.genome[chrom] = seq
                    chrom = line.strip()[1:]**.split(" ")[0]**
                    seq = ''
                    print(chrom)
                else:
                    seq += line.strip().upper()

Not sure if this is maybe worth adding in because I don't think it will break normally formatted fastas.

Best,
Charlotte

**Comment by jpaggi** [comment]
Hi Charlotte,

Thanks so much for pointing this out!

Fixing this is a great idea. Would you be able to submit a pull request (so you're properly credited)? I'll commit this code in a few days if not.

Best,
Joe

**Comment by CharlotteAnne** [comment]
Hi Joe!

I've done it, hopefully correctly, this is the first time I've done this :P

Thanks for the help!

Charlotte
