### ISSUE TITLE
Model initialisation

### ISSUE THREAD

**Issue by CharlotteAnne** [jpaggi/labranchor#2]
Hi,

When learning the BPs I get the following warning message:

Using TensorFlow backend.
Loading sequences from hg38_gencode_v29_3SS_seqs.fa
Read 208571 sequences
Loading model from ../../software/labranchor/labranchor/2layer.h5
2018-10-30 14:37:18.897478: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/****/software/miniconda2/lib/python2.7/site-packages/keras/engine/saving.py:327: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '

Is this something that will affect the predictions (I get output that looks sensible!), or is it safe to ignore this?

Thanks for your help,
Charlotte

**Comment by jpaggi** [comment]
This isn't an issue for prediction.

(The root of this seems to be that the formatting of how the optimizer is stored changed somewhat between versions of keras, but this doesn't affect the predictions.)

**Comment by Trandamere** [comment]
I also failed to install TensorFlow, which is always missing something.
